#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 11 09:56:34 2022

@author: maximsecor
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import time as time
import os
import sys
import seaborn as sns

from keras.models import Sequential,load_model
from keras.layers import Dense, Activation, Flatten, Dropout, Conv1D, MaxPooling1D
from keras.optimizers import Adam
import keras.backend as K

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error 

import warnings 
warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore', category=DeprecationWarning)

np.set_printoptions(precision=4,suppress=True)

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf

#%%

file_features = '/Users/maximsecor/Desktop/MNC/Cleaned_ANN_input_Data/Feature_Selected/RFE_16.csv'
df_features = pd.read_csv(file_features)
RFE = df_features.values

file_features = '/Users/maximsecor/Desktop/MNC/Cleaned_ANN_input_Data/OOH_UHF/UHF_density_matrices_full.csv'
df_features = pd.read_csv(file_features)
features = df_features.values

#%%

print(RFE[0])
print(features[0])

#%%

for i in range(16):
    print(matrix_orb_list[np.where(features[0]==RFE[0][i])[0][0]])
    print(np.where(features[0]==RFE[0][i])[0][0])



